Fixed some issues
kandidatg11/behaviour-activation pull request #73
Opened 2021-05-19 14:03 UTC by malin-mallan

2021-05-19 14:14 UTC, malin-mallan commented
I tried på fix #69 as well but not sure if I did it right

2021-05-20 09:55 UTC, EMattfolk requested changes

2021-05-20 09:55 UTC, EMattfolk commented on src/language/LanguageProvider.tsx
> +const LanguageContext = createContext(en);
This is not enough to change the default. You need to change the default setting in storage as well.

2021-05-20 09:55 UTC, EMattfolk commented on src/language/en.tsx
> +        BehaviouralActivation: 'Behavioral Activation',
The name would also have to be changed in `app.json` . The repo should probably also be renamed.

2021-05-20 14:47 UTC, EMattfolk approved these changes

2021-05-20 14:47 UTC, EMattfolk commented on app.json
> +    "slug": "BehaviouralActivation",
```suggestion
    "slug": "BehavioralActivation",
```

2021-05-21 17:22 UTC, Neathan approved these changes

2021-05-23 14:39 UTC, merged